import type { Theme, NotificationTemplate } from "./types";

export const SAMPLE_TEMPLATES: Record<Theme, NotificationTemplate[]> = {
  epic_meaning: [
    { title: "Tera English journey sirf tere liye nahi hai", body: "Jab tu seekhta hai, teri poori family ko confidence milta hai. 10L+ learners started.", cta: "Join the mission", image: "Family smiling as learner practices English at home" },
    { title: "Kuch bada hone wala hai", body: "Story mein hero ne apna career change kiya. Teri story abhi shuru hui hai.", cta: "Start your chapter", image: "Sunrise over a city skyline, new beginning energy" },
    { title: "Tu akela nahi hai is journey mein", body: "10L+ learners ne interview crack kiya. Ab teri baari hai.", cta: "Begin your story", image: "Crowd of learners celebrating together" },
    { title: "Ek decision jo sab badal dega", body: "Is chapter mein wo skills hain jo life change kar dein. Ready?", cta: "Change your story", image: "Fork in the road, one path glowing with light" },
    { title: "Hero ki journey teri inspiration hai", body: "Chapter mein dream job ke liye tayyari ho rahi hai. Tu bhi kar sakta hai.", cta: "Start the journey", image: "Character studying with determination at desk" },
    { title: "Confident banna sirf ek chapter door hai", body: "English seekhke zindagi badli ja sakti hai. Tera chapter wait kar raha hai.", cta: "Open chapter", image: "Confident person speaking at podium" },
    { title: "Teri calling aa rahi hai", body: "Professional English seekhna sirf skill nahi \u2014 career ka turning point hai.", cta: "Answer the call", image: "Phone ringing with opportunity icon" },
    { title: "Sapne bade hain, pehla kadam chhota", body: "Har badi journey ek chhote step se shuru hoti hai. Aaj wo step le.", cta: "Take first step", image: "Footsteps leading toward a bright horizon" },
  ],
  accomplishment: [
    { title: "Chapter complete \u2014 tu unstoppable hai! \ud83d\udd25", body: "87% score aaya hai. Bahut kam log itna jaldi reach karte hain.", cta: "Keep the streak alive", image: "Trophy with fire emoji, celebration confetti" },
    { title: "New badge unlocked!", body: "Chapter complete \u2014 'Confident Speaker' badge earned. Ab next level.", cta: "See your badges", image: "Shiny badge with star, unlock animation" },
    { title: "Top 15% learners mein aa gaya tu", body: "Score dekh \u2014 hero bhi proud hoga tujhpe.", cta: "See your rank", image: "Leaderboard with user highlighted in top section" },
    { title: "50 words mastered \u2014 vocab king! \ud83d\udc51", body: "Chapter se 38 new words add hue. Collection growing fast.", cta: "See your vault", image: "Word vault overflowing with golden words" },
    { title: "Halfway mark crossed!", body: "Aadha safar complete. Momentum mat rok.", cta: "Continue learning", image: "Progress bar at 50% with celebration" },
    { title: "Tera consistency kamal hai", body: "7 din continuous learning \u2014 ye habit ban rahi hai. Keep going.", cta: "Next lesson", image: "Calendar with 7 days streak marked green" },
    { title: "Chapter 87% done", body: "Bas 2 lessons aur \u2014 scene complete hone wala hai.", cta: "Finish strong", image: "Finish line ribbon almost within reach" },
    { title: "Score all-time high hai!", body: "Pichle chapter se 12% zyada score aaya. Growth real hai.", cta: "View progress", image: "Graph showing upward trend with star at peak" },
  ],
  empowerment: [
    { title: "Aaj kya seekhna hai? Tu decide kar", body: "Multiple paths ready hain. Tera pace, tera choice.", cta: "Choose your path", image: "Three colorful doors to choose from" },
    { title: "Struggling? Koi baat nahi", body: "Easy mode try kar, ya topic switch kar. Learning tera, rules bhi tere.", cta: "Customize difficulty", image: "Difficulty slider with friendly hand adjusting" },
    { title: "3 paths open hain \u2014 tu choose kar", body: "Vocabulary, Speaking, ya Practice \u2014 kaunsa mood hai aaj?", cta: "Pick your lesson", image: "Three branching paths in a garden" },
    { title: "Tera learning, teri speed", body: "Chapter tera wait kar raha hai. Jab ready ho, tab start kar.", cta: "Start when ready", image: "Play button with relaxed clock icon" },
    { title: "New challenge ya revision? Tu bol", body: "Dono options hain \u2014 confident feel kar toh aage badh.", cta: "Decide now", image: "Two cards: Challenge vs Revision" },
    { title: "Skills teri superpower ban sakti hai", body: "Hero ne choose kiya confident banna \u2014 ab tera turn hai.", cta: "Make your choice", image: "Superhero cape with English book" },
    { title: "Ek nayi skill unlock karne ka mann hai?", body: "5 tracks mein se koi bhi try kar. No pressure.", cta: "Explore tracks", image: "Map with multiple unlocked paths" },
    { title: "Comfort zone ya growth zone?", body: "Dono valid hain \u2014 par aaj kya choose karega?", cta: "You decide", image: "Two zones separated by a glowing line" },
  ],
  ownership: [
    { title: "Tera vocabulary vault: 247 words strong \ud83d\udcb0", body: "Naye words add hue. Collection growing \u2014 don\u2019t stop now.", cta: "See your vault", image: "Golden vault with words floating inside" },
    { title: "12-day streak saved hai", body: "Ek aur din add kar aur Gold Streak unlock ho jayega. Tune ye earn kiya.", cta: "Protect your streak", image: "Fire streak counter with shield icon" },
    { title: "Tera progress portfolio dekh", body: "Multiple chapters, 247 words, 12 badges \u2014 ye sab tune build kiya.", cta: "View portfolio", image: "Portfolio folder bursting with achievements" },
    { title: "Chapter 67% tera hai", body: "Itna progress tune mehnat se banaya. Thoda push \u2014 complete ho jayega.", cta: "Continue building", image: "Building under construction, 67% complete" },
    { title: "5 badges earned \u2014 collection badh rahi hai", body: "Har badge teri skill ka proof hai. Next badge sirf 1 lesson door.", cta: "Earn next badge", image: "Badge collection display with one slot glowing" },
    { title: "Tera learning history impressive hai", body: "30 lessons complete, 87% avg score \u2014 ye stats tere hain.", cta: "See your stats", image: "Dashboard with impressive stats highlighted" },
    { title: "Chapter mein tera 67% invest hai", body: "Itna effort waste mat hone de. Thoda aur push \u2014 chapter tera.", cta: "Complete chapter", image: "Investment graph showing progress invested" },
    { title: "Tune ye library khud banayi hai", body: "Har seekha hua word teri personal library mein hai. Proud moment.", cta: "Open your library", image: "Personal bookshelf with glowing books" },
  ],
  social_influence: [
    { title: "Tera batch aage nikal gaya \ud83d\udc40", body: "236 learners ne chapter complete kiya is week. Tu kahan hai?", cta: "Catch up", image: "Group of learners racing ahead on a track" },
    { title: "Community mein celebration ho rahi hai", body: "Chapter mein hero ne scene crack kiya \u2014 4.8K celebrations.", cta: "See the moment", image: "Confetti and community cheering together" },
    { title: "1,847 learners ne aaj start kiya", body: "Chapter trending hai. Tu bhi join kar sakta hai.", cta: "Join them", image: "Trending arrow with crowd of learners" },
    { title: "Tera friend aage nikal gaya", body: "892 learners tujhse aage hain. Gap close kar.", cta: "Start now", image: "Friend waving from ahead on the learning path" },
    { title: "Top performer of the week kaun?", body: "Leaderboard mein naye names aaye hain. Tera rank dekh.", cta: "Check leaderboard", image: "Leaderboard with crown on top position" },
    { title: "Community mein scene viral hai", body: "Chapter ka twist \u2014 2.3K learners ne react kiya. Tu ne dekha?", cta: "See reactions", image: "Viral post with reaction emojis floating" },
    { title: "Teri city mein 500+ learners active hain", body: "Local learners top kar rahe hain. Join the wave.", cta: "Join your city", image: "City map with active learner dots" },
    { title: "Sabse popular chapter right now", body: "Is week ka most-completed chapter \u2014 tu ne try kiya?", cta: "Try trending", image: "Fire icon on most popular chapter card" },
  ],
  scarcity: [
    { title: "Bonus content \u2014 48 hrs left \u23f3", body: "Special practice section sirf limited time ke liye open hai.", cta: "Start before it locks", image: "Hourglass with sand running out, locked door" },
    { title: "Tera early access expire ho raha hai", body: "New chapter kal lock ho jayega. Abhi try kar.", cta: "Open now", image: "Access card with expiry countdown" },
    { title: "Sirf aaj \u2014 bonus tips", body: "Secret hacks chapter mein unlock hain. Kal lock ho jayenge.", cta: "Unlock today", image: "Golden key with Today Only banner" },
    { title: "Limited spots: Practice round", body: "Sirf top 500 learners ke liye. 312 spots bache hain.", cta: "Reserve spot", image: "Seats filling up with countdown number" },
    { title: "Weekend special chapter unlock hua", body: "Confidence booster \u2014 sirf Sunday tak available. 1,200 ne start kiya.", cta: "Start now", image: "Weekend badge with unlock animation" },
    { title: "Exclusive: Secret prep guide", body: "Ye bonus content sirf 24 hours ke liye hai. 847 already started.", cta: "Access guide", image: "Exclusive stamp on glowing guide book" },
    { title: "Time running out on bonus", body: "Hidden section 6 hours mein lock hoga. Miss mat kar.", cta: "Open before lock", image: "Clock ticking with lock closing animation" },
    { title: "Flash challenge \u2014 2 hours only", body: "Special quiz sirf abhi available hai. Top scorers get badge.", cta: "Take challenge", image: "Lightning bolt with timer showing 2:00:00" },
  ],
  unpredictability: [
    { title: "Hero ne kuch unexpected kaha... \ud83d\ude2e", body: "Chapter mein twist \u2014 kya result milega? Sirf ek tarika hai jaanne ka.", cta: "Find out", image: "Speech bubble with question marks" },
    { title: "Mystery challenge unlocked \ud83c\udf81", body: "Hidden bonus round hai. Koi nahi batayega \u2014 khud discover kar.", cta: "Open surprise", image: "Gift box with glowing question mark" },
    { title: "Chapter mein kuch unexpected hai...", body: "Scene mein ek twist hai jo kisi ne predict nahi kiya.", cta: "Discover it", image: "Door slightly open with light peeking through" },
    { title: "Ek secret lesson chhupa hai \ud83d\udd0d", body: "Chapter mein hidden content hai. Pehle kisiko nahi mila.", cta: "Find the secret", image: "Magnifying glass revealing hidden text" },
    { title: "Story ka climax aa raha hai", body: "Chapter ka climax aa raha hai. Answer sirf andar milega.", cta: "See what happens", image: "Dramatic curtain about to open" },
    { title: "Surprise reward waiting for you", body: "Hidden achievement hai. Hint: vocabulary se related hai.", cta: "Claim reward", image: "Treasure chest with sparkle effect" },
    { title: "Plot twist alert \u26a1", body: "Hero ne kuch aisa kaha \u2014 result unexpected hai. Dekhega?", cta: "Watch the twist", image: "Lightning bolt striking open book" },
    { title: "Kuch naya discover karne ka mann?", body: "Ek hidden path hai jo sirf curious learners ko milta hai.", cta: "Explore hidden path", image: "Secret path behind waterfall in forest" },
  ],
  loss_avoidance: [
    { title: "Tera 15-day streak danger mein hai \u26a0\ufe0f", body: "Sirf 5-min lesson karke streak save kar le. Effort waste mat hone de.", cta: "Save my streak", image: "Streak fire flickering, about to go out" },
    { title: "Chapter ka progress fade ho raha hai", body: "67% complete tha \u2014 3 din aur skip kiya toh review se start.", cta: "Continue now", image: "Progress bar slowly fading to grey" },
    { title: "Tera vocabulary rust ho raha hai", body: "38 words seekhe the \u2014 bina practice ke bhool jayega. 5 min de.", cta: "Quick revision", image: "Words fading from memory cloud" },
    { title: "Scene chhoot raha hai", body: "Chapter adhoora hai \u2014 hero ka dream tujhpe depend karta hai.", cta: "Don\u2019t leave hero", image: "Character looking back waiting for user" },
    { title: "3 din ho gaye \u2014 progress at risk", body: "Chapter mein itna aage aaya tha. Ab mat ruk.", cta: "Resume learning", image: "Warning triangle on progress dashboard" },
    { title: "Tera rank slip ho raha hai", body: "Top 15% se bahar ja raha hai tu. Ek lesson se wapas aa sakta hai.", cta: "Reclaim rank", image: "Rank arrow pointing downward with alert" },
    { title: "Badge expire hone wala hai \u23f0", body: "Consistent Learner badge 2 din mein expire hoga. Ek lesson = saved.", cta: "Save badge", image: "Badge with countdown timer overlay" },
    { title: "Mehnat waste mat hone de", body: "Itne din ki learning ek break se reset ho sakti hai. Protect kar.", cta: "Protect progress", image: "Shield protecting a progress bar from breaking" },
  ],
};
